// This is a basic service worker for PWA functionality
// It will be auto-generated by Create React App's build process
// This file is a placeholder for custom service worker logic if needed

self.addEventListener('install', (event) => {
  console.log('Service Worker installing.');
});

self.addEventListener('activate', (event) => {
  console.log('Service Worker activating.');
});

self.addEventListener('fetch', (event) => {
  // Basic fetch handler - CRA will provide more sophisticated caching
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});

